### ISSUE TITLE
specified buildpack fails

### ISSUE THREAD

**Issue by mimecine** [josegonzalez/dokku-wordpress#41]
Just tried this procedure and it failed until I removed the .buildpacks file and let herokuish select it's own buildpack. FYI.

**Comment by kwyatt242** [comment]
I confirm the same. Commenting out the line below comment "# adding .env file to configure buildpack" did the trick!

**Comment by josegonzalez** [comment]
Update the buildpack version we specify in our Makefile via a PR and it should work fine.

**Comment by mimecine** [comment]
Wish I had dared to dip my toes into making a PR. Next time I will
muster...
