### ISSUE TITLE
.htaccess rewrite rules

### ISSUE THREAD

**Issue by fi0** [josegonzalez/dokku-wordpress#42]
Pages become 404 when the app is restarted. How do I flush the rewrite rules automatically?
Or can I make it persistent?

**Comment by albertovaccarella** [comment]
@fi0 did you find a solution? just tried my first dokku+wordpress deploy and I run into this as well.
I managed to fix it by adding an .htaccess file to the root of the repository using the rewrite rules described here:

https://www.hostinger.com/tutorials/fix-404-error-wordpress

**Comment by josegonzalez** [comment]
Commit the changes to the repository? As dokku runs apps in containers, any changes to the internal disk in unmounted paths won't persist through app restarts/rebuilds, and there isn't anything you can do about that.

**Comment by babarinde** [comment]
You can do

`dokku storage:mount app-name /var/lib/dokku/data/storage/app-name/.htaccess:/app/.htaccess`
Works on restart/rebuilds
