### ISSUE TITLE
Installation doesn't configure php-gd correctly

### ISSUE THREAD

**Issue by ironfroggy** [josegonzalez/dokku-wordpress#9]
This breaks resizing and cropping uploaded photos.

This can be fixed by just adding `"ext-gd": "*"` to composer.json requirements

**Comment by josegonzalez** [comment]
Pull requests welcome!

**Comment by josegonzalez** [comment]
Closed by #12.

**Comment by josegonzalez** [comment]
Re-opening as the composer.lock needs to also be updated.

**Comment by axilleas** [comment]
@josegonzalez I guess you can now close this :) `composer.lock` updated in https://github.com/dokku-community/dokku-wordpress/commit/699293642fe23ed7b96c8e274a679e3995292539
